# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

# Build settings
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

# Sphinx configuration
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false  # Set to true once docs are stable

# Python settings
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs

# Submodules (if needed)
submodules:
  include: []
  recursive: false

# Formats to build
formats:
  - pdf
  - epub
